root = "."
tmp_dir = "../tmp"

[build]
cmd = "go build -o ../tmp/main ./cmd/server/main.go"
bin = "../tmp/main"
full_bin = "../tmp/main"
include_ext = ["go", "html", "css"]
exclude_dir = ["tmp", "vendor"]
delay = 1000
kill_delay = "0.5s"
stop_on_error = true