services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - PORT=8080
      - DB_PATH=/data/retrospec.db
    volumes:
      - .:/app
      - sqlite_data:/data

volumes:
  sqlite_data: